"""add book_requests table

Revision ID: 04bf49922011
Revises: 2d3fede5f7da
Create Date: 2026-01-09 08:06:25.548154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bf49922011'
down_revision = '2d3fede5f7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_requests_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_requests_requester_id'), ['requester_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_book_requests_book_id'))

    op.drop_table('book_requests')
    # ### end Alembic commands ###
