"""Add security events table

Revision ID: 893e39e1240e
Revises: 63ab63c6d94f
Create Date: 2026-01-14 08:05:41.848661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893e39e1240e'
down_revision = '63ab63c6d94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.Column('blueprint', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_blueprint'), ['blueprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_books_deleted_by_id'))
        batch_op.drop_constraint(batch_op.f('fk_books_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_books_deleted_by_id'), ['deleted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_status_code'))
        batch_op.drop_index(batch_op.f('ix_security_events_role'))
        batch_op.drop_index(batch_op.f('ix_security_events_ip'))
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_endpoint'))
        batch_op.drop_index(batch_op.f('ix_security_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_security_events_blueprint'))

    op.drop_table('security_events')
    # ### end Alembic commands ###
